Adex : consent logs for adex RSP
datakaveri/iudx-rs-proxy pull request #56
Opened 2023-12-14 05:15 UTC by ananjaykumar2

Duplicate of  #55 and additional changes : 

- [x] Signing log with PKCS certificate
- [x] Logging consent flow (Apiserver --> optional consent log verticle)
- [x] Pushing audit message to audit server

 **Note** : Junit pending.

2023-12-15 07:14 UTC, ankitmashu requested changes

2023-12-15 07:14 UTC, ankitmashu commented on src/main/java/iudx/rs/proxy/optional/consentlogs/ConsentLoggingServiceImpl.java
> +                .forItemType(jwtData.getType())
Make sure , item_type should be in UPPERCASE

2024-01-04 10:31 UTC, pranavrd commented on src/main/java/iudx/rs/proxy/apiserver/ApiServerVerticle.java
>      return ppbno;
could be replaced with `return cons.getString("ppbNumber", "");` to avoid NPE

2024-01-05 04:22 UTC, ankitmashu approved these changes
LGTM

2024-01-19 12:59 UTC, merged